# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_Category', models.TextField(blank=True, default='')),
                ('Exam_Name', models.TextField(blank=True, default='')),
                ('Exam_Sections', models.TextField(blank=True, default='')),
                ('Exam_Topics', models.TextField(blank=True, default='')),
                ('Is_Master', models.BooleanField(default=False)),
                ('Created_Time', models.DateTimeField(auto_now_add=True)),
                ('Updated_Time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
